version: "3.8"
services:
  database:
    container_name: "journal-postgresql"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresJournal
      POSTGRES_USER: userJournal
      POSTGRES_PASSWORD: passwordJournal